#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { Command } from 'commander'
import { glob } from 'glob'
import { detectConfig } from './cli-detection'
import { c, separator, symbols } from './cli-style'
import { cleanupTranslations } from './translations-cleanup'
import { loadConfig } from './config/loader'
import { mergeWithDefaults, validateConfig } from './config/validator'
import { runExtraction } from './extract-strings/orchestrator'
import { detectI18nPatterns } from './extract-strings/i18nPatternDetector'
import { translateMissingKeys } from './extract-strings/autoTranslate'
import { createAIClient } from './ai/client'
import type { ToolConfig } from './config/types'

function readPkgVersion(): string {
  try {
    const pkgPath = path.resolve(__dirname, '../package.json')
    const pkgRaw = fs.readFileSync(pkgPath, 'utf-8')
    const pkg = JSON.parse(pkgRaw) as { version?: string }
    return pkg.version || process.env.npm_package_version || '0.0.0'
  }
  catch {
    return process.env.npm_package_version || '0.0.0'
  }
}

const program = new Command()

program
  .name('vue-translations-cleanup')
  .description('Clean up unused translation keys in your i18n files')
  .version(readPkgVersion())
  .option('-t, --translation-file <path>', 'Path to translation file or directory (if omitted, try auto-detect)')
  .option('-s, --src-path <path>', 'Path to source files (if omitted, try auto-detect)')
  .option('-c, --config <path>', 'Path to config file (vue-translations-cleanup.config.{ts,mjs,json})')
  .option('--init', 'Generate a config file with detected settings')
  .option('--extract', 'Extract raw strings and create i18n keys (instead of cleanup)')
  .option('--translate', 'Translate missing/untranslated keys to target languages (requires AI)')
  .option('-n, --dry-run', 'Show what would be removed/changed without making changes')
  .option('--no-backup', 'Skip creating backup file')
  .option('-v, --verbose', 'Show detailed output')
  .option('-p, --pattern <glob>', 'File pattern to scan (default: "**/*.{vue,js,ts}")')

program.parse()

const options = program.opts()

/**
 * Generate config file content with detected settings
 */
function generateConfigContent(settings: {
  translationFile: string
  srcPath: string
  targetLanguage: string
  customPattern?: { functionName: string, example: string, importStatement?: string }
}): string {
  const { translationFile, srcPath, targetLanguage, customPattern } = settings

  // Build i18nPatterns array only if custom pattern is provided
  let patternsCode = ''
  if (customPattern) {
    // Use the example as the import template
    const importTemplate = customPattern.example

    // Escape special regex characters in the pattern
    const escapedTemplate = importTemplate.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const regexPattern = escapedTemplate.replace(/\\s\\*/g, '\\\\s*')

    // Use detected import statement or provide a default based on the pattern
    let importStatementStr = customPattern.importStatement
    if (!importStatementStr && importTemplate.includes('useI18n')) {
      importStatementStr = "import { useI18n } from 'vue-i18n'"
    }

    patternsCode = `
    // Custom i18n pattern detected - please review and adjust if needed
    i18nPatterns: [
      {
        pattern: /${regexPattern}/,
        functionName: '${customPattern.functionName}',
        importTemplate: '${importTemplate}',
        importStatement: '${importStatementStr || ''}',
        injectLocation: 'script-setup',
      },
    ],`
  }

  return `import type { ToolConfig } from 'vue-translations-cleanup'

/**
 * Configuration for vue-translations-cleanup
 * Generated by: npx vue-translations-cleanup --init
 */
const config: ToolConfig = {
  // Detected paths
  // translationFile: directory containing translation JSON files (e.g., en.json, de.json)
  // The specific file is determined by extract.targetLanguage
  translationFile: '${translationFile}',
  srcPath: '${srcPath}',

  // Extraction settings
  extract: {
    // Target language determines which file to update (e.g., 'en' -> en.json)
    targetLanguage: '${targetLanguage}',
    keyFormat: 'snake_case',
    maxKeyLength: 50,${patternsCode}
  },

  // AI translation (optional)
  ai: {
    enabled: false,
    provider: 'ollama',
    model: 'codellama',
    // languages: ['de', 'fr'],  // Uncomment to auto-translate
  },

  // Backup and output options
  backup: true,
  verbose: false,
  dryRun: false,
}

export default config
`
}

async function run() {
  // === INIT MODE ===
  if (options.init) {
    console.log(c.strong('\n=== Config Generator ===\n'))

    const configFileName = 'vue-translations-cleanup.config.ts'
    const configFilePath = path.join(process.cwd(), configFileName)

    // Check if config already exists
    if (fs.existsSync(configFilePath)) {
      console.error(c.error(`${symbols.error} Config file already exists: ${configFileName}`))
      console.error(c.dim('Delete or rename the existing file to generate a new one.'))
      process.exit(1)
    }

    console.log(c.dim(`${symbols.info} Detecting project configuration...`))

    // Detect paths and i18n settings
    const detected = await detectConfig(process.cwd())
    const cwd = process.cwd()

    // Convert absolute paths to relative and use directory for translations
    let translationDir = detected.translationsPath || './locales'
    let srcPathRel = detected.srcPath || './src'

    // Convert to relative paths if absolute
    if (path.isAbsolute(translationDir)) {
      translationDir = './' + path.relative(cwd, translationDir)
    }
    if (path.isAbsolute(srcPathRel)) {
      srcPathRel = './' + path.relative(cwd, srcPathRel)
    }

    // If translation path is a file, use its directory
    if (translationDir.endsWith('.json')) {
      translationDir = path.dirname(translationDir)
    }

    // Use detected locale or default to 'en'
    const targetLanguage = detected.defaultLocale || 'en'

    console.log(c.dim(`  Translation directory: ${translationDir}`))
    console.log(c.dim(`  Source path: ${srcPathRel}`))
    console.log(c.dim(`  Default locale: ${targetLanguage}`))

    // Determine which case we're in based on detection results
    let customPattern: { functionName: string, example: string, importStatement?: string } | undefined
    let needsUserReview = false

    // Case 1: Config found with globalInjection enabled (default) - use $t
    if (detected.configType && detected.globalInjection !== false) {
      console.log(c.dim(`  i18n config: ${detected.configType} (using $t)`))
      // No custom pattern needed - $t is available globally
    }
    // Case 2: Need to scan for i18n usage
    else {
      console.log(c.dim(`${symbols.info} Scanning for i18n usage patterns...`))

      const srcDir = detected.srcPath
        ? path.resolve(process.cwd(), detected.srcPath)
        : path.join(process.cwd(), srcPathRel)

      if (fs.existsSync(srcDir)) {
        try {
          const result = await detectI18nPatterns(srcDir, '**/*.vue')

          if (result.recommendedPattern) {
            const pattern = result.recommendedPattern

            // Check if it's a standard $t pattern
            if (pattern.functionName === '$t' || pattern.type === 'global') {
              console.log(c.dim(`  Found $t() usage (${pattern.count} occurrences)`))
              // No custom pattern needed
            }
            else {
              // Custom pattern detected (e.g., useI18n, injectContext, etc.)
              console.log(c.dim(`  Found ${pattern.functionName}() pattern (${pattern.count} occurrences)`))

              customPattern = {
                functionName: pattern.functionName,
                example: pattern.example,
                importStatement: pattern.importStatement,
              }
              needsUserReview = true
            }
          }
          else {
            // Case 3: No i18n usage found
            console.error(c.error(`\n${symbols.error} No i18n usage detected in your project.`))
            console.error(c.dim('\nThis tool requires existing i18n setup in your project.'))
            console.error(c.dim('Please ensure you have:'))
            console.error(c.dim('  - vue-i18n or @nuxtjs/i18n installed'))
            console.error(c.dim('  - At least one translation function call ($t, t, etc.)'))
            console.error(c.dim('\nAlternatively, create the config file manually.'))
            process.exit(1)
          }
        }
        catch (error) {
          console.log(c.warn(`  ${symbols.warn} Could not scan for patterns: ${(error as Error).message}`))
        }
      }
      else {
        // Source directory not found - Case 3
        console.error(c.error(`\n${symbols.error} Source directory not found: ${srcDir}`))
        console.error(c.dim('Please create the config file manually.'))
        process.exit(1)
      }
    }

    // Generate config content
    const configContent = generateConfigContent({
      translationFile: translationDir,
      srcPath: srcPathRel,
      targetLanguage,
      customPattern,
    })

    // Write config file
    fs.writeFileSync(configFilePath, configContent, 'utf-8')

    console.log(c.success(`\n${symbols.success} Config file created: ${configFileName}`))

    if (needsUserReview) {
      console.log(c.warn(`\n${symbols.warn} Custom i18n pattern detected.`))
      console.log(c.dim('Please review the generated config file and ensure the i18nPatterns'))
      console.log(c.dim('section is correct for your setup, especially the importStatement.'))
    }

    console.log(c.dim('\nYou can now run:'))
    console.log(c.dim(`  npx vue-translations-cleanup            # cleanup mode`))
    console.log(c.dim(`  npx vue-translations-cleanup --extract  # extract mode`))
    console.log(c.dim(`  npx vue-translations-cleanup --translate # translate mode (requires AI)`))

    return
  }

  // Load config file if provided
  let config: ToolConfig | null = null
  if (options.config) {
    const configPath = path.resolve(process.cwd(), options.config)
    config = await loadConfig(path.dirname(configPath), configPath)

    if (!config) {
      console.error(`Config file not found: ${options.config}`)
      process.exit(1)
    }

    // Validate and merge with defaults
    validateConfig(config)
    config = mergeWithDefaults(config)

    if (options.verbose) {
      console.log(c.info(`${symbols.info} Loaded config from: ${options.config}`))
    }
  }
  else {
    // Try to auto-load config
    config = await loadConfig(process.cwd())

    if (config) {
      validateConfig(config)
      config = mergeWithDefaults(config)

      if (options.verbose) {
        console.log(c.info(`${symbols.info} Auto-loaded config file`))
      }
    }
  }

  let translationTarget: string | undefined = options.translationFile || config?.translationFile
  let srcPath: string | undefined = options.srcPath || config?.srcPath

  // Auto-detect when missing
  if (!translationTarget || !srcPath) {
    const detected = await detectConfig(process.cwd())
    if (!translationTarget && detected.translationsPath)
      translationTarget = detected.translationsPath
    if (!srcPath && detected.srcPath)
      srcPath = detected.srcPath

    if (options.verbose) {
      console.log(separator('Auto-detection'))
      console.log(c.strong('[vue-translations-cleanup] Auto-detection:'))
      console.log(c.dim(`${symbols.info} srcPath:`), srcPath || c.warn('not detected'))
      console.log(c.dim(`${symbols.info} translationsPath:`), translationTarget || c.warn('not detected'))
      if (detected.reason)
        console.log(c.dim(`${symbols.warn} note:`), detected.reason)
    }
  }

  if (!translationTarget || !srcPath) {
    console.error('Could not determine required paths. Please specify:')
    console.error('  -t, --translation-file <path-to-file-or-directory>')
    console.error('  -s, --src-path <path-to-source>')
    console.error('  or provide a config file with --config')
    process.exit(1)
  }

  // === TRANSLATE MODE ===
  if (options.translate) {
    let absTranslations = path.resolve(process.cwd(), translationTarget)

    // Ensure config is loaded (use defaults if not)
    if (!config) {
      config = mergeWithDefaults({})
    }

    // Check if AI is enabled
    if (!config.ai?.enabled || !config.ai?.languages || config.ai.languages.length === 0) {
      console.error(c.error(`\n${symbols.error} Translation mode requires AI to be enabled with target languages.`))
      console.error(c.dim('\nPlease configure AI in your config file:'))
      console.error(c.dim('  ai: {'))
      console.error(c.dim('    enabled: true,'))
      console.error(c.dim('    provider: \'ollama\', // or \'anthropic\', \'openai\', etc.'))
      console.error(c.dim('    languages: [\'de\', \'fr\', \'es\'], // target languages'))
      console.error(c.dim('  }'))
      process.exit(1)
    }

    // Check if translations target is a directory
    const isDir = fs.existsSync(absTranslations) && fs.statSync(absTranslations).isDirectory()

    if (isDir) {
      // Use targetLanguage from config to determine the source file
      const targetLang = config.extract?.targetLanguage || 'en'
      absTranslations = path.join(absTranslations, `${targetLang}.json`)

      if (options.verbose) {
        console.log(c.dim(`${symbols.info} Using source translation file: ${absTranslations}`))
      }
    }

    // Check if source translation file exists
    if (!fs.existsSync(absTranslations)) {
      console.error(c.error(`\n${symbols.error} Source translation file not found: ${absTranslations}`))
      process.exit(1)
    }

    console.log(c.strong('\n=== Translation Sync Mode ===\n'))
    console.log(c.dim(`Source file: ${absTranslations}`))
    console.log(c.dim(`Target languages: ${config.ai.languages.join(', ')}\n`))

    try {
      // Create AI client
      const aiClient = createAIClient(config.ai)

      if (!aiClient) {
        console.error(c.error(`\n${symbols.error} Failed to create AI client. Please check your AI configuration.`))
        process.exit(1)
      }

      // Run translation
      const result = await translateMissingKeys({
        sourceFile: absTranslations,
        targetLanguages: config.ai.languages,
        aiClient,
        sourceLanguage: config.extract?.targetLanguage || 'en',
        excludePatterns: config.ai.excludeFromTranslation,
        backup: options.backup,
        verbose: options.verbose,
      })

      // Display results
      if (result.translatedLanguages.length > 0) {
        console.log(c.success(`\n${symbols.success} Translation completed in ${result.duration}ms`))
        console.log(c.dim('\nSummary:'))
        for (const [lang, count] of Object.entries(result.translationsPerLanguage)) {
          if (count > 0) {
            console.log(c.dim(`  ${lang}: ${count} keys translated`))
          }
        }

        if (result.errors.length > 0) {
          console.log(c.warn(`\n${symbols.warn} Errors encountered:`))
          for (const { language, error } of result.errors) {
            console.error(c.dim(`  ${language}: ${error}`))
          }
        }
      }
      else {
        console.log(c.info(`\n${symbols.info} All translations are up to date`))

        if (result.errors.length > 0) {
          console.log(c.warn(`\n${symbols.warn} Errors encountered:`))
          for (const { language, error } of result.errors) {
            console.error(c.dim(`  ${language}: ${error}`))
          }
        }
      }
    }
    catch (error) {
      console.error(c.error(`\n${symbols.error} Translation failed:`), error)
      process.exit(1)
    }

    return
  }

  // === EXTRACT MODE ===
  if (options.extract) {
    let absTranslations = path.resolve(process.cwd(), translationTarget)
    const absSrc = path.resolve(process.cwd(), srcPath)

    // Ensure config is loaded (use defaults if not)
    if (!config) {
      config = mergeWithDefaults({})
    }

    // Check if translations target is a directory
    const isDir = fs.existsSync(absTranslations) && fs.statSync(absTranslations).isDirectory()

    if (isDir) {
      // Use targetLanguage from config to determine the file
      const targetLang = config.extract?.targetLanguage || 'en'
      absTranslations = path.join(absTranslations, `${targetLang}.json`)

      if (options.verbose) {
        console.log(c.dim(`${symbols.info} Using translation file: ${absTranslations}`))
      }
    }

    console.log(c.strong('\n=== String Extraction Mode ===\n'))

    try {
      await runExtraction({
        translationFile: absTranslations,
        srcPath: absSrc,
        config: config!, // config is guaranteed to be non-null here due to check above
        dryRun: options.dryRun,
        verbose: options.verbose,
      })
    }
    catch (error) {
      console.error(c.error(`\n${symbols.error} Extraction failed:`), error)
      process.exit(1)
    }

    return
  }

  // === CLEANUP MODE (default) ===

  // Resolve to absolute paths
  const absTranslations = path.resolve(process.cwd(), translationTarget)
  const absSrc = path.resolve(process.cwd(), srcPath)
  // Try to detect if translations target is a directory; if stat fails, treat as file
  let isDir = false
  try {
    isDir = fs.statSync(absTranslations).isDirectory()
  }
  catch {
    isDir = false
  }

  if (!isDir) {
    const translationFile = absTranslations
    const result = await cleanupTranslations({
      translationFile,
      srcPath: absSrc,
      backup: options.backup,
      dryRun: options.dryRun,
      verbose: options.verbose,
    })

    if (options.verbose) {
      console.log('\nResults:')
      console.log('Total translation keys:', result.totalKeys)
      console.log('Used keys:', result.usedKeys)
      console.log('Unused keys:', result.unusedKeys)
    }
    else {
      console.log(c.info(`\n${symbols.info} Found ${result.unusedKeys} unused translation keys out of ${result.totalKeys} total keys`))
    }

    if (result.unusedKeys > 0) {
      if (options.verbose) {
        console.log('\nUnused translations:')
        console.log(result.unusedTranslations.join('\n'))
      }

      if (options.dryRun) {
        console.log(c.dim('\nDry run - no changes made'))
      }
      else if (result.cleaned) {
        console.log(c.success(`\n${symbols.success} Translations file has been updated: ${translationFile}`))
        if (options.backup) {
          console.log(c.dim(`Backup created at: ${translationFile}.backup`))
        }
      }
    }
    else {
      console.log(c.success(`\n${symbols.success} No unused translations found`))
      if (result.cleaned && !options.dryRun) {
        console.log(c.dim(`Pruned empty groups. Translations file has been updated: ${translationFile}`))
        if (options.backup) {
          console.log(c.dim(`Backup created at: ${translationFile}.backup`))
        }
      }
    }

    return
  }

  // Directory mode
  const jsons = await glob('**/*.json', { cwd: absTranslations, nodir: true })
  const files = jsons.map(rel => path.join(absTranslations, rel))
  if (files.length === 0) {
    console.error(`No JSON files found in directory: ${absTranslations}`)
    process.exit(1)
  }
  if (options.verbose) {
    console.log(separator(`Found ${files.length} translation files`))
    console.log(c.dim(absTranslations))
  }

  let totalUnused = 0
  let anyCleaned = false

  for (const file of files) {
    const result = await cleanupTranslations({
      translationFile: file,
      srcPath: absSrc,
      backup: options.backup,
      dryRun: options.dryRun,
      verbose: options.verbose,
    })

    totalUnused += result.unusedKeys
    anyCleaned = anyCleaned || result.cleaned

    if (options.verbose) {
      console.log(`\n${c.info(`[${path.relative(process.cwd(), file)}] -> unused: ${result.unusedKeys}/${result.totalKeys}`)}`)
      if (result.unusedKeys > 0) {
        console.log(c.strong('Unused translations:'))
        console.log(result.unusedTranslations.join('\n'))
      }
      if (result.cleaned && !options.dryRun) {
        console.log(c.success(`Updated file (backup ${options.backup ? 'created' : 'skipped'})`))
      }
    }
  }

  if (!options.verbose) {
    console.log(c.info(`\n${symbols.info} Found ${totalUnused} unused translation keys across ${files.length} file(s)`))
  }

  if (totalUnused === 0) {
    console.log(c.success(`\n${symbols.success} No unused translations found`))
    if (anyCleaned && !options.dryRun)
      console.log(c.dim('Pruned empty groups. Some translation files were updated.'))
  }
}

run().catch((error) => {
  console.error('Error:', error.message)
  process.exit(1)
})
